---
- name: Ensure backup directory exists
  file:
    path: '{{ openshift_template_backup_dest_path }}'
    state: directory
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'

- name: Backup {{ openshift_template_ksc }} ns templates
  shell: |
    oc -n {{ openshift_template_ksc }} \
    get templates -o yaml --export > {{ openshift_template_backup_dest_path }}/sc_templates.yaml
  ignore_errors: yes

- name: Backup {{ openshift_template_ksc }} ns clusterserviceclass
  shell: |
    oc -n {{ openshift_template_ksc }} \
    get clusterserviceclass -o yaml --export > {{ openshift_template_backup_dest_path }}/sc_clusterserviceclasses.yaml
  ignore_errors: yes

- name: Backup openshift ns templates
  shell: |
    oc -n openshift \
    get templates -o yaml --export > {{ openshift_template_backup_dest_path }}/openshift_sc_templates.yaml

# ansible-doc s3_sync
- name: Sync backup templates to {{ aws_s3_backup_bucket }} bucket
  s3_sync:
    bucket: '{{ aws_s3_backup_bucket }}'
    region: '{{ aws_region }}'
    key_prefix: '{{ openshift_template_backup_prefix }}/'
    file_root: '{{ openshift_template_backup_root }}/{{ openshift_template_backup_prefix }}/'
    mode: push
    permission: private
    file_change_strategy: date_size
  delegate_to: localhost
  run_once: true
  when: aws_s3 is defined and aws_s3 | bool
  tags: s3_sync
